### ISSUE TITLE
value does not get reset

### ISSUE THREAD

**Issue by taviisaicu** [ellipticaljs/paper-autocomplete#34] opened 2016-11-03 15:04 UTC
Using Remote Data-Source Binding, after a selection was made and then the text is cleared, the value is not set to null, still has the value of the previous selection

**Comment by jhuesos** [comment] 2016-11-11 07:49
Can you elaborate in the steps to reproduce it?

Do you mean that after clicking in the X the input field does not get resetted? I noticed today that if you click in the X to reset the input field, the functionality is not working. I am looking into it now

**Comment by jhuesos** [comment] 2016-11-11 08:30
I have just released a new version **v1.5.1** that fixes the reset button:

now after you select a value, if you click on reset button, the value is reset as expected. This was happening with both type of data-sources: remote and loca.

Can you please test and validate that this fixes the problem you were having? If the issue is fixed, please close the issue. And it is not, please provide more information.

And for your information, I opened an issue to collect feedback about changing the reset button behavior and visibility. It would be great if you could go to that issue and share your opinion or expectations.

Thanks

**Comment by jhuesos** [comment] 2016-11-15 12:11
As far as I know this issue has been fixed. So I am closing it. Feel free to re-open if there are any other scenario that is still not fixed.

**Closed as completed by jhuesos** 2016-11-15 12:11 UTC
Labels: bug
