### ISSUE TITLE
polymer 2.0 error

### ISSUE THREAD

**Issue by neckaros** [ellipticaljs/paper-autocomplete#70] opened 2017-05-23 21:38 UTC
Hello,

i get the following error when running on polymer 2.0 :

`<paper-autocomplete id="my-id" label="Select" ></paper-autocomplete>`

```
Uncaught TypeError: Cannot read property 'localName' of undefined (template-stamp.html:228)
    at Function._parseTemplateNode (template-stamp.html:228) 
    at Function._parseTemplateNode (property-effects.html:2303)
    at Function._parseTemplateContent (template-stamp.html:210)
    at Function._parseTemplateContent (element-mixin.html:777)
    at Function._parseTemplate (template-stamp.html:204)
    at Object.templatize (templatize.html:405)
    at HTMLElement.templatize (templatizer-behavior.html:93)
    at HTMLElement.ready (paper-autocomplete-suggestions.html:401)
    at HTMLElement.ready (class.html:207)
    at HTMLElement._enableProperties (property-accessors.html:494)
```
do you plan todo aversion compatible with polymer 2.0?

**Comment by jhuesos** [comment] 2017-05-24 06:37
There is a Pull Request open to make the component hybrid and compatible with Polymer 2.0. If everything goes okay, I will be merging it today. I will try to reproduce your issue in that new branch

**Comment by jhuesos** [comment] 2017-05-24 06:46
By the way, can you provide more information about how to reproduce this error? You just update to polymer 2.0 and that's it?

**Comment by neckaros** [comment] 2017-05-24 17:19
No i have a brand new Polymer 2.0 project (created with polymer cli) and installed the bower with the command provided here.
If i add the import i have no issue.
If i add the sample code below in my page i have the error:
`<paper-autocomplete id="my-id" label="Select" ></paper-autocomplete>`
I will try again with your merge as soon as it is available

**Comment by jhuesos** [comment] 2017-05-28 16:34
I will be merging a PR to the branch **2.0-preview** soon. Unfortunately, we cannot release it yet because it does not work with IE11. If you do not care much about IE11, then it is safe to say you should be fine using it. Please, let me know if you find any other issues with that version.

**Comment by neckaros** [comment] 2017-05-29 19:20
Ok i will test and report back when merged.
I tried a commit from the pull request and still had some issue. But might be due to the way i use it. i will try with the 2.0-preview an report

**Comment by jhuesos** [comment] 2017-05-29 20:28
Awesome. Please let me know how it goes.

In the longer term, I am planning to re-write the component making it only compatible with Polymer 2.0 maintaining backward compatibility. But I will try to gather some feedback and keep two versions for sometime.

**Comment by neckaros** [comment] 2017-05-30 21:15
Not sure where i should report issues?
i'm using code from the demo:
```
<paper-autocomplete label="Add tag" on-autocomplete-selected="_selectionTagAdd" id="inputlocal" no-label-float="true" source="[[tags]]"
          text-property="fullPath" value-property="id" style="flex: 1;">
          <template slot="autocomplete-custom-template">
            <style>
               :host {
                display: block;
              }
              paper-item.account-item {
                padding: 8px 16px;
              }
              .company-name {
                color: #333;
              }
              .account-number {
                margin-top: 4px;
                color: #999;
              }
            </style>
            <paper-item on-tap="_onTap" id$="[[_getSuggestionId(index)]]" role="option" aria-selected="false">
              <div>
                <div class="company-name">[[item.name]]</div>
                <div class="account-number">[[item.fullPath]]</div>
              </div>
              <paper-ripple></paper-ripple>
            </paper-item>
          </template>
        </paper-autocomplete>
```
 ```
_queryFn(datasource, query) {
        query = query.toLowerCase();
        var compare = function (a, b) {
          if (a.name < b.name)
            return -1;
          if (a.name > b.name)
            return 1;
          return 0;
        };
        return datasource.filter(function (item) {
          return (item.fullPath.toLowerCase().indexOf(query) != -1);
        }).sort(compare).splice(0, 15);
      }
```
and i get errors when I enter text:
`method `_getSuggestionId` not defined`

when i use keyboard everything seems to work but when i click on an item i get:
`template-stamp.html:94 listener method `_onTap` not defined`
i tried with _onSelect from documentation but also got the error

![capture d ecran 4](https://cloud.githubusercontent.com/assets/7789770/26605316/cfea9b2a-458d-11e7-818a-ddd2567aedd2.png)

otherwise it seems ok :)

**Comment by neckaros** [comment] 2017-05-31 07:13
I fixed both issue by implementing _onTap & _onSelect and _getSuggestionId in my code contrary to current API documentation.
I guess it is a limitation of slotting with WebComponents 1.0.

**Comment by jhuesos** [comment] 2017-05-31 10:30
That is a regression. That shouldn't be the case. But you are right, it might be a limitation of the shadow v1 slots. I am going to look into it. Thanks again for helping us testing :)

**Comment by neckaros** [comment] 2017-06-01 18:25
Glad i can help. Great component

**Comment by jhuesos** [comment] 2017-07-16 10:21
@neckaros I pushed a new version in the `2.0-preview` branch that should be fixed the issues you reported here.

Can you pull the latest version and verify if that is true. And if that's the case, close this issue? Many thanks nin advance

**Comment by neckaros** [comment] 2017-07-16 16:41
It seems 2.0-preview branch does not exist anymore

**Comment by jhuesos** [comment] 2017-07-16 17:39
Yes, sorry. I should have told you that today I released v3.0.0. you can
try it there

**Comment by neckaros** [comment] 2017-07-16 20:35
Working like a charm!
Thanks so much

**Comment by jhuesos** [comment] 2017-07-17 05:38
Thanks again for testing. Cheers

**Closed as completed by jhuesos** 2017-07-17 05:38 UTC
Labels: feedback_needed
