### ISSUE TITLE
Suggestion uses wrong property

### ISSUE THREAD

**Issue by RehkitzDev** [ellipticaljs/paper-autocomplete#103] opened 2017-12-14 13:49 UTC
I've implemented the paper-autocomplete in a paper-dialog the following way:
`<paper-autocomplete source="{{ajaxResponse}}" text-property="name" value-property="id" highlight-first></paper-autocomplete>`

My source looks like this: 
`{"id":"5a0c2cb71c56350df086787f","name":"Adjektiv"},
{"id":"5a0c2cb71c56350df0867880","name":"Artikel"} ...`

The outout is this:
![image](https://user-images.githubusercontent.com/4146348/33994537-26edeba0-e0db-11e7-96f0-29a0f62ad96f.png)

When i click one specific suggestion, the paper-autocomplete element works as intended, but it doesn't show the suggestion text.

When i looked into the "_getItemText" function in the paper-autocomplete-suggestion.html i noticed that the suggestion array has "key" & "value" properties and the function uses "name" as the text property.

I'm sorry if i missed something in my implementation.

**Comment by christianaye** [comment] 2018-01-23 12:53
is a duplicate of #66.

**Closed as completed** 2018-01-28 10:06 UTC
